### ISSUE TITLE
textual_fspicker doesn't work with python 3.9

### ISSUE THREAD

**Issue by feizheng10** [davep/textual-fspicker#55]
We are trying to use textual_fspicker with python 3.9
Got the error: ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib64/python3.9/typing.py)
The root cause is: TypeAlias was introduced in Python 3.10.

Technically, the alternative solutions could be:
(a) Update to python >= 3.10.
(b) Try to workaround for everywhere in textual_fspicker with the below:

try:
from typing import TypeAlias # Python 3.10+
except ImportError:
try:
from typing_extensions import TypeAlias # For older Python versions
except ImportError:
from typing import Any as TypeAlias # Final fallback for runtime only

Solution (a) might not work well as some potential customers still expect to run it RHEL 9 with the default python 3.9
Solution (b), is it worthy raising an issue or fixing this way?

Any other suggestions?

**Comment by davep** [comment]
`TypeAlias` is intended to be pulled from `typing_extensions` for just this reason, you can see that elsewhere:

```
$ rg "from typing.*TypeAlias"
src/textual_fspicker/base_dialog.py
11:from typing import Callable, TypeAlias

src/textual_fspicker/path_filters.py
14:from typing_extensions import TypeAlias
```

The instance of it coming from `typing` in `base_dialog.py` is just a mistake. I'll tweak that.

**Comment by davep** [comment]
[v0.4.2 is now available](https://github.com/davep/textual-fspicker/releases/tag/v0.4.2) which should fix this issue. Thanks for letting me know about it!

**Comment by feizheng10** [comment]
Sounds like we need:


from typing import Callable, Union

MyType: TypeAlias = Union[str, Callable[[str], str]]

**Comment by davep** [comment]
Are you sure?

```
$ python --version
Python 3.9.6
$ cat test.py
from __future__ import annotations

def test(value: str | int) -> None:
    print(type(value))

test("One")
test(1)

$ python test.py
<class 'str'>
<class 'int'>
```

**Comment by davep** [comment]
Okay, let's try again: [0.4.3](https://github.com/davep/textual-fspicker/releases/tag/v0.4.3).
